language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "8.0"
    - php: "nightly"
  allow_failures:
    - php: "8.0"
    - php: "nightly"

services:
    - memcached
    - mysql
    - postgresql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    - psql -c 'create database travis_ci_test;' -U postgres

install:
    - composer self-update
    - composer update

script:
    #######################
    # Test without caching
    #######################

    # Test SQLite
    - php bin/install.php
    - php bin/make-tables.php
    - composer test
    - composer static-analysis
    # Test MySQL
    - php bin/install.php --mysql --host 127.0.0.1 -u root --database test
    - php bin/make-tables.php
    - composer test
    - composer static-analysis
    # Test PostgreSQL
    - php bin/install.php --pgsql -u postgres --database travis_ci_test
    - php bin/make-tables.php
    - composer test
    - composer static-analysis

    #####################
    # Test with caching
    #####################

    # Enable Cache
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    # Test SQLite
    - php bin/install.php
    - composer test
    - composer static-analysis
    # Test MySQL
    - php bin/install.php --mysql --host 127.0.0.1 -u root --database test
    - composer test
    - composer static-analysis
    # Test PostgreSQL
    - php bin/install.php --pgsql -u postgres --database travis_ci_test
    - composer test
    - composer static-analysis
